name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: zwerminal-linux
            asset_name: zwerminal-linux
          - os: windows-latest
            artifact_name: zwerminal.exe
            asset_name: zwerminal-windows.exe
          - os: macos-latest
            artifact_name: zwerminal
            asset_name: zwerminal-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rich pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --console main.py --name zwerminal
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          zwerminal-linux/zwerminal-linux
          zwerminal-windows.exe/zwerminal-windows.exe  
          zwerminal-macos/zwerminal-macos
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
